
### Get all recent positions
GET http://localhost:23032/api/posizioneflotta HTTP/1.1

### Post a position message
POST http://localhost:23032/api/messaggiPosizione HTTP/1.1
Content-Type: application/json

{
    "codiceMezzo": "APS.54321",
    "classiMezzo": [ "APS", "benzina" ],
    "localizzazione": {
        "lat": 14.3347,
        "lon": 43.4321
    },
    "istanteAcquisizione": "2018-06-25T20:16:00.1234Z",
    "fonte": {
        "codiceFonte": "AH222",
        "classeFonte": "gpsTracker"
    },
    "infoFonte": {
    
    }
}

### InRettangolo
GET http://localhost:23032/api/inRettangolo?lat1=14.30&lon1=43.42&lat2=14.3346&lon2=43.44 HTTP/1.1